import { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { HelloWorldRes } from "../interfaces/HelloWorld";

const Home: NextPage = () => {
  const [data, setData] = useState<HelloWorldRes | null>(null);

  useEffect(() => {
    const fetchData = async (): Promise<void> => {
      try {
        const response = await fetch("api/hello");
        const data = (await response.json()) as HelloWorldRes;
        setData(data);
      } catch (error) {
        console.error("Error occurred while fetching data", error);
      }
    };
    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>Blogify App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Create <span className="text-purple-300">Blogs</span> Here
        </h1>
        <p className="text-2xl text-gray-700">Coming soon!</p>
        {data ? <p>{data.text}</p> : <p>API Data Loading...</p>}
      </main>
    </>
  );
};

export default Home;
